Repository sisoputnfrba/so-commons-library, pull requests merged in 2022-08, with the labels that each got.

#158 Build: Actualizo Docker image al nuevo entorno
  .dockerignore
  Dockerfile
  src/makefile
Labels: build

#155 Log: actualizo descripción de config_create
  src/commons/config.h
Labels: docs

#134 Strings: replace y n_append
  src/commons/string.c
  src/commons/string.h
  tests/unit-tests/test_string.c
Labels: feature

#159 Yet Another List Refactor
  src/commons/collections/list.c
  src/commons/collections/list.h
  tests/unit-tests/test_list.c
Labels: refactor, tests

#162 Build: GitHub Actions
  .github/workflows/unit-tests.yml
  .travis.yml
  makefile
Labels: build

#161 feat: api para manejo de timestamps (#156)
  src/commons/temporal.c
  src/commons/temporal.h
  tests/integration-tests/temporal/main.c
Labels: feature
