Repository sisoputnfrba/so-commons-library, pull requests merged in 2022-03, with the labels that each got.

#146 Update log.h
  src/commons/log.h
Labels: docs

#150 Update list_is_empty and queue_is_empty
  src/commons/collections/list.c
  src/commons/collections/list.h
  src/commons/collections/queue.c
  src/commons/collections/queue.h
Labels: enhancement

#152 Fix Dockerfile
  Dockerfile
Labels: fix
